# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lz/Desktop/FServerless

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lz/Desktop/FServerless

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lz/Desktop/FServerless/CMakeFiles /home/lz/Desktop/FServerless/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lz/Desktop/FServerless/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named control

# Build rule for target.
control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 control
.PHONY : control

# fast build rule for target.
control/fast:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/build
.PHONY : control/fast

FuncFactory.o: FuncFactory.cpp.o

.PHONY : FuncFactory.o

# target to build an object file
FuncFactory.cpp.o:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/FuncFactory.cpp.o
.PHONY : FuncFactory.cpp.o

FuncFactory.i: FuncFactory.cpp.i

.PHONY : FuncFactory.i

# target to preprocess a source file
FuncFactory.cpp.i:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/FuncFactory.cpp.i
.PHONY : FuncFactory.cpp.i

FuncFactory.s: FuncFactory.cpp.s

.PHONY : FuncFactory.s

# target to generate assembly for a file
FuncFactory.cpp.s:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/FuncFactory.cpp.s
.PHONY : FuncFactory.cpp.s

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.s
.PHONY : client.cpp.s

control.o: control.cpp.o

.PHONY : control.o

# target to build an object file
control.cpp.o:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/control.cpp.o
.PHONY : control.cpp.o

control.i: control.cpp.i

.PHONY : control.i

# target to preprocess a source file
control.cpp.i:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/control.cpp.i
.PHONY : control.cpp.i

control.s: control.cpp.s

.PHONY : control.s

# target to generate assembly for a file
control.cpp.s:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/control.cpp.s
.PHONY : control.cpp.s

function.o: function.cpp.o

.PHONY : function.o

# target to build an object file
function.cpp.o:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/function.cpp.o
.PHONY : function.cpp.o

function.i: function.cpp.i

.PHONY : function.i

# target to preprocess a source file
function.cpp.i:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/function.cpp.i
.PHONY : function.cpp.i

function.s: function.cpp.s

.PHONY : function.s

# target to generate assembly for a file
function.cpp.s:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/function.cpp.s
.PHONY : function.cpp.s

node.o: node.cpp.o

.PHONY : node.o

# target to build an object file
node.cpp.o:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/node.cpp.o
.PHONY : node.cpp.o

node.i: node.cpp.i

.PHONY : node.i

# target to preprocess a source file
node.cpp.i:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/node.cpp.i
.PHONY : node.cpp.i

node.s: node.cpp.s

.PHONY : node.s

# target to generate assembly for a file
node.cpp.s:
	$(MAKE) -f CMakeFiles/control.dir/build.make CMakeFiles/control.dir/node.cpp.s
.PHONY : node.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... rebuild_cache"
	@echo "... control"
	@echo "... FuncFactory.o"
	@echo "... FuncFactory.i"
	@echo "... FuncFactory.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... control.o"
	@echo "... control.i"
	@echo "... control.s"
	@echo "... function.o"
	@echo "... function.i"
	@echo "... function.s"
	@echo "... node.o"
	@echo "... node.i"
	@echo "... node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

