#拉取docker环境
FROM python 

#设置工作目录
WORKDIR /function 

#将dockerfile同级目录的文件传到docker容器内的app文件夹下
ADD Fhttp.py /function 
ADD main.py /function 
# # ADD requirements.txt /app

# # RUN pip install flask -i https://pypi.mirrors.ustc.edu.cn/simple/

# # EXPOSE 80

# # ENV NAME World


# #运行python的命令
CMD python main.py 